POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

curl -X 'POST' \
  'http://192.168.32.154/api/v2.0/auth/check_password' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer 1-unUUaD8po4VnBdFBIJGBnzJA1Abom2LGyuULys9MSggoNV8DFik2Uql1jPHwcOiU" \
  -d '{
  "username": "admin",
  "password": "tjorven"
}'

###

curl -X 'GET' \
  'http://192.168.32.154/api/v2.0/disk' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer 1-unUUaD8po4VnBdFBIJGBnzJA1Abom2LGyuULys9MSggoNV8DFik2Uql1jPHwcOiU" \
    -d '{
}'

###

curl -X 'GET' \
  'http://192.168.32.154/api/v2.0/pool' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer 1-unUUaD8po4VnBdFBIJGBnzJA1Abom2LGyuULys9MSggoNV8DFik2Uql1jPHwcOiU" \
    -d '{
}'

###

curl -X 'POST' \
  'http://192.168.32.154/api/v2.0/pool' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer 1-3bkv5czpXcODKCtX5Lo95ua5N9DTzJ3y99qHhWcW4ejOin8ETWaor7rPIFGV7UDB" \
  -d '{
  "name": "jippieee",
  "encryption": false,
  "deduplication": null,
  "checksum": null,
  "topology": {
    "data": [
      {
        "type": "STRIPE",
        "disks": [
          "sdb","sdc"
        ]
      }
    ],
    "cache": [
      {
        "type": "STRIPE",
        "disks": [
          
        ]
      }
    ],
    "log": [
      {
        "type": "STRIPE",
        "disks": [
          
        ]
      }
    ],
    "spares": [
      
    ]
  },
  "allow_duplicate_serials": true
}'

###

curl -X 'GET' \
  'http://192.168.32.154/api/v2.0/chart/release' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer 1-3bkv5czpXcODKCtX5Lo95ua5N9DTzJ3y99qHhWcW4ejOin8ETWaor7rPIFGV7UDB" \
    -d '{
}'

###
#default login = admin wachtwoord = changeme
curl -X POST "http://192.168.32.154/api/v2.0/chart/release" \
      -H 'accept: application/json' \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer 1-3bkv5czpXcODKCtX5Lo95ua5N9DTzJ3y99qHhWcW4ejOin8ETWaor7rPIFGV7UDB" \
     -d '{
           "catalog": "TRUENAS",
           "item": "nextcloud",
           "release_name": "nextcloud-release",
           "train": "charts",
           "version": "1.6.56",
           "values": {
              # Additional configuration parameters specific to your Nextcloud setup
           }
         }'
